"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import * as z from "zod";
import { Loader2 } from "lucide-react";

import { cn } from "@/lib/utils";
import { registerSchema } from "@/schemas/validation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { createClient } from "@/lib/supabase/client";
import { RoleSelection } from "./role-selection";
import {
    DEFAULT_STUDENT_LOGIN_REDIRECT,
    DEFAULT_SUPERVISOR_LOGIN_REDIRECT,
} from "@/lib/routes";

interface RegisterFormProps extends React.ComponentPropsWithoutRef<"div"> { }

type RegisterValues = z.infer<typeof registerSchema>;

export function RegisterForm({ className, ...props }: RegisterFormProps) {
    const [error, setError] = React.useState<string | null>(null);
    const [isLoading, setIsLoading] = React.useState(false);
    const [selectedRole, setSelectedRole] = React.useState<"STUDENT" | "SUPERVISOR">("STUDENT");

    const {
        register,
        handleSubmit,
        setValue,
        formState: { errors },
    } = useForm<RegisterValues>({
        resolver: zodResolver(registerSchema),
        defaultValues: {
            email: "",
            password: "",
            name: "",
            surname: "",
            role: "STUDENT",
        },
    });

    const onRoleChange = (role: "STUDENT" | "SUPERVISOR") => {
        setSelectedRole(role);
        setValue("role", role);
    };

    async function onSubmit(data: RegisterValues) {
        setIsLoading(true);
        setError(null);

        const supabase = createClient();

        try {
            // 1. Sign up the user with metadata for the trigger
            const { data: authData, error: signUpError } = await supabase.auth.signUp({
                email: data.email,
                password: data.password,
                options: {
                    data: {
                        role: data.role,
                        name: data.name,
                        surname: data.surname,
                    },
                },
            });

            if (signUpError) throw signUpError;
            if (!authData.user) throw new Error("Registration failed. No user returned.");

            // 2. Insert into role-specific table
            // The trigger public.handle_new_user() creates the user_profile.
            // We manually add the entry to students/supervisors table.
            // NOTE: user_id is the FK to user_profiles.id (auth.uid())
            //       id is auto-generated by the database.
            if (data.role === "STUDENT") {
                const { error: studentError } = await supabase
                    .from("students")
                    .insert({
                        user_id: authData.user.id,
                    });
                if (studentError) throw studentError;
            } else {
                const { error: supervisorError } = await supabase
                    .from("supervisors")
                    .insert({
                        user_id: authData.user.id,
                    });
                if (supervisorError) throw supervisorError;
            }

            const redirectUrl = data.role === "STUDENT"
                ? DEFAULT_STUDENT_LOGIN_REDIRECT
                : DEFAULT_SUPERVISOR_LOGIN_REDIRECT;

            window.location.assign(redirectUrl);
        } catch (err: any) {
            setError(err.message || "Something went wrong during registration.");
            setIsLoading(false);
        }
    }

    return (
        <div className={cn("grid gap-6", className)} {...props}>
            <form onSubmit={handleSubmit(onSubmit)}>
                <div className="grid gap-4">
                    <div className="grid gap-2">
                        <Label className="text-sm font-medium">I am a...</Label>
                        <RoleSelection
                            selectedRole={selectedRole}
                            onSelectRole={onRoleChange}
                        />
                    </div>

                    <div className="grid grid-cols-2 gap-4">
                        <div className="grid gap-2">
                            <Label htmlFor="name">First Name</Label>
                            <Input
                                id="name"
                                placeholder="John"
                                disabled={isLoading}
                                {...register("name")}
                            />
                            {errors.name && (
                                <p className="text-sm text-destructive">{errors.name.message}</p>
                            )}
                        </div>
                        <div className="grid gap-2">
                            <Label htmlFor="surname">Last Name</Label>
                            <Input
                                id="surname"
                                placeholder="Doe"
                                disabled={isLoading}
                                {...register("surname")}
                            />
                            {errors.surname && (
                                <p className="text-sm text-destructive">{errors.surname.message}</p>
                            )}
                        </div>
                    </div>

                    <div className="grid gap-2">
                        <Label htmlFor="email">Email</Label>
                        <Input
                            id="email"
                            placeholder="name@example.com"
                            type="email"
                            autoCapitalize="none"
                            autoComplete="email"
                            autoCorrect="off"
                            disabled={isLoading}
                            {...register("email")}
                        />
                        {errors.email && (
                            <p className="text-sm text-destructive">{errors.email.message}</p>
                        )}
                    </div>

                    <div className="grid gap-2">
                        <Label htmlFor="password">Password</Label>
                        <Input
                            id="password"
                            placeholder="Create a password"
                            type="password"
                            autoComplete="new-password"
                            disabled={isLoading}
                            {...register("password")}
                        />
                        {errors.password && (
                            <p className="text-sm text-destructive">{errors.password.message}</p>
                        )}
                    </div>

                    {error && (
                        <div className="p-3 text-sm font-medium text-destructive bg-destructive/10 rounded-md">
                            {error}
                        </div>
                    )}

                    <Button type="submit" className="w-full" disabled={isLoading}>
                        {isLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                        Create account
                    </Button>
                </div>
            </form>
        </div>
    );
}
